services:
  - type: web
    name: rag-chat-backend
    env: python
    buildCommand: pip install --no-deps -r requirements.txt
    startCommand: python Backend/main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    runtime: python3.11